import semantics.Symbol.Type;
/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnd extends TypeNode {
  public ASTAnd(int id) {
    super(id);
    type = Type.BOOL;
  }

  public ASTAnd(Parser p, int id) {
    super(p, id);
    type = Type.BOOL;
  }

}
/* JavaCC - OriginalChecksum=1766d5431be81e19119cf5feee80cd49 (do not edit this line) */
