/* Generated By:JJTree: Do not edit this line. ASTAssignVarArray.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignVarArray extends SimpleNode {
  public String arrayIdentifier;
  public ASTAssignVarArray(int id) {
    super(id);
  }

  public ASTAssignVarArray(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0fabe93ca61357985801f024c411ccd1 (do not edit this line) */
