import semantics.Symbol.Type;

/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBooleanValue extends TypeNode {
  public boolean bool;

  public ASTBooleanValue(int id) {
    super(id);
    type = Type.BOOL;
  }

  public ASTBooleanValue(Parser p, int id) {
    super(p, id);
    type = Type.BOOL;
  }

  public String toString() {
    return ParserTreeConstants.jjtNodeName[id] + "[" + bool + "]";
  }
}
/* JavaCC - OriginalChecksum=3a15dd3418ff85dee49e992d4b407151 (do not edit this line) */
