import semantics.Symbol.Type;

/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends TypeNode {
  public ASTDiv(int id) {
    super(id);
    type = Type.INT;
  }

  public ASTDiv(Parser p, int id) {
    super(p, id);
    type = Type.INT;
  }

}
/* JavaCC - OriginalChecksum=a6ae99679f76890aff99ebcee897988e (do not edit this line) */
