import semantics.Symbol.Type;

/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifier extends TypeNode {
  public String identifierName;

  public ASTIdentifier(int id) {
    super(id);
    type = Type.OBJ;
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
    type = Type.OBJ;
  }

  public String toString() {
    return ParserTreeConstants.jjtNodeName[id] + "[" + identifierName + "]";
  }

//  @Override
//  public void eval() throws SemanticsException {
//    if(!this.table.checkSymbol(identifierName)) throw new SemanticsException("Symbol '" + identifierName + "' has not been declared.");
//  }
}
/* JavaCC - OriginalChecksum=75abfe948da46b0c7b3a59b2cae3a666 (do not edit this line) */
