import semantics.Symbol.Type;
/* Generated By:JJTree: Do not edit this line. ASTLessThan.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThan extends TypeNode {
  public ASTLessThan(int id) {
    super(id);
    type = Type.BOOL;
  }

  public ASTLessThan(Parser p, int id) {
    super(p, id);
    type = Type.BOOL;
  }

}
/* JavaCC - OriginalChecksum=c0d8a8972c0a4b4df64282733df15850 (do not edit this line) */
