import semantics.Symbol;

/* Generated By:JJTree: Do not edit this line. ASTLength.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLength extends TypeNode {
  public ASTLength(int id) {
    super(id);
    type = Symbol.Type.INT;
  }

  public ASTLength(Parser p, int id) {
    super(p, id);
    type = Symbol.Type.INT;
  }

}
/* JavaCC - OriginalChecksum=d20841b9a326e3b2ada1a7a0c3a4a9a1 (do not edit this line) */
