import semantics.SymbolTable;

/* Generated By:JJTree: Do not edit this line. ASTMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethod extends SimpleNode {
  public ASTMethod(int id) {
    super(id);
  }

  public ASTMethod(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws SemanticsException {
    if (this.jjtGetNumChildren() != 2) throw new SemanticsException("Lacks the number of required children!");
    SimpleNode methodType = (SimpleNode) this.jjtGetChild(0);
    final SymbolTable table = new SymbolTable();

    if (methodType.id == ParserTreeConstants.JJTMETHODNAME){
      //TODO: Are you supposed to have a method symbol table or not?
    } else if(methodType.id == ParserTreeConstants.JJTMAIN) {
      //TODO: Denote as main
    } else {
      throw new SemanticsException("No method type was found");
    }

    SimpleNode methodBody = (SimpleNode) this.jjtGetChild(1);
    if(methodBody.id != ParserTreeConstants.JJTMETHODBODY)
      throw new SemanticsException("No method body found!");
    methodBody.setTable(table);
    methodBody.eval();

  }
}
/* JavaCC - OriginalChecksum=e01bdf01dd9e8aa606ef225a59a26df3 (do not edit this line) */
