import semantics.Symbol.Type;

/* Generated By:JJTree: Do not edit this line. ASTMul.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMul extends TypeNode {
  public ASTMul(int id) {
    super(id);
    type = Type.INT;
  }

  public ASTMul(Parser p, int id) {
    super(p, id);
    type = Type.INT;
  }

}
/* JavaCC - OriginalChecksum=e5abe143d74eea8d5312703bd5001c7a (do not edit this line) */
