import semantics.Symbol.Type;

/* Generated By:JJTree: Do not edit this line. ASTMinus.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinus extends BinaryOperatorNode {
  public ASTMinus(int id) {
    super(id,Type.INT,Type.INT);
  }

  public ASTMinus(Parser p, int id) {
    super(p, id,Type.INT,Type.INT);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.INT};
  }
}
/* JavaCC - OriginalChecksum=bbfd8df0d693716f262be0a04e48a128 (do not edit this line) */
