/* Generated By:JJTree: Do not edit this line. ASTNegation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNegation extends SimpleNode {
  public ASTNegation(int id) {
    super(id);
  }

  public ASTNegation(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9c3764f7a642e8c835bbe49b3f9238b (do not edit this line) */
