/* Generated By:JJTree: Do not edit this line. ASTNumeric.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumeric extends SimpleNode {
  public int number;
  public ASTNumeric(int id) {
    super(id);
  }

  public ASTNumeric(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1df27becc141526f727d9a5e4174f25 (do not edit this line) */
