/* Generated By:JJTree: Do not edit this line. ASTNewType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewType extends SimpleNode {
  public ASTNewType(int id) {
    super(id);
  }

  public ASTNewType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49389771733e22744a19132f4a028989 (do not edit this line) */
