/* Generated By:JJTree: Do not edit this line. ASTNewArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewArray extends SimpleNode {
  public ASTNewArray(int id) {
    super(id);
  }

  public ASTNewArray(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ee8df6c7c664939c9c61c61a7786c8a (do not edit this line) */
