/* Generated By:JJTree: Do not edit this line. ASTStuff.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStuff extends SimpleNode {
  public ASTStuff(int id) {
    super(id);
  }

  public ASTStuff(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac23c01d4568c1402fbad6274caa6931 (do not edit this line) */
