/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import semantics.Symbol;

public
class ASTVar extends ASTVarDeclaration {
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3558354610a208fcf13fa1f04295551 (do not edit this line) */
