/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.5 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTIMPORTSTATEMENT = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTSTATEMENT = 6;
  public int JJTSTUFF = 7;
  public int JJTEXPRESSION = 8;
  public int JJTTYPE = 9;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ImportStatement",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Statement",
    "Stuff",
    "Expression",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=759588c49963a1431a9fbe0edc72146e (do not edit this line) */
