/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.5 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTSTUFF = 2;
  public int JJTARRAYACCESS = 3;
  public int JJTMETHODCALL = 4;
  public int JJTEXPRESSION = 5;
  public int JJTNUMERIC = 6;
  public int JJTNEW = 7;
  public int JJTNEWARRAY = 8;
  public int JJTNEGATION = 9;
  public int JJTTYPE = 10;
  public int JJTNEWTYPE = 11;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Stuff",
    "ArrayAccess",
    "MethodCall",
    "Expression",
    "Numeric",
    "New",
    "NewArray",
    "Negation",
    "Type",
    "NewType",
  };
}
/* JavaCC - OriginalChecksum=497760eb33283dbde248554a2059b4f8 (do not edit this line) */
