/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.1_2 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTIMPORTSTATEMENT = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTSTATEMENT = 6;
  public int JJTSTUFF = 7;
  public int JJTVOID = 8;
  public int JJTTYPE = 9;
  public int JJTNEW = 10;
  public int JJTEXPRESSION = 11;
  public int JJTARRAYACCESS = 12;
  public int JJTNUMERIC = 13;
  public int JJTNEGATION = 13;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ImportStatement",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Statement",
    "Stuff",
    "void",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=898a523c522e87c751ad2b665b3771f7 (do not edit this line) */
