package javamm.parser;

import javamm.semantics.Symbol.Type;
import java.io.PrintWriter;
/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnd extends BinaryOperatorNode {
  public ASTAnd(int id) {
    super(id,Type.BOOL,Type.BOOL);
  }

  public ASTAnd(Javamm p, int id) {
    super(p, id,Type.BOOL,Type.BOOL);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.BOOL};
  }

  @Override
  public void write(PrintWriter writer) {
    //TODO implement this or leave blank to not call the default one
  }
}
/* JavaCC - OriginalChecksum=1766d5431be81e19119cf5feee80cd49 (do not edit this line) */
