package javamm.parser;

import javamm.semantics.StackUsage;
import javamm.semantics.Symbol.Type;

import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBooleanValue extends TypeNode {
  public boolean bool;

  public ASTBooleanValue(int id) {
    super(id);
    type = Type.BOOL;
  }

  public ASTBooleanValue(Javamm p, int id) {
    super(p, id);
    type = Type.BOOL;
  }

  public String toString() {
    return JavammTreeConstants.jjtNodeName[id] + "[" + bool + "]";
  }

  @Override
  public void write(PrintWriter writer) {
    writer.println("  iconst_" + (bool ? 1 : 0));
  }

  @Override
  protected void calculateStackUsage(StackUsage stackUsage) {
    stackUsage.inc(1);
  }
}
/* JavaCC - OriginalChecksum=3a15dd3418ff85dee49e992d4b407151 (do not edit this line) */
