package javamm.parser;

import javamm.SemanticsException;
import javamm.semantics.ClassSymbol;
import javamm.semantics.MethodSymbolTable;
import javamm.semantics.SymbolTable;

/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClass extends SimpleNode {
  public ClassSymbol classSymbol;

  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws SemanticsException {
    final MethodSymbolTable newTable = new MethodSymbolTable(methodTable);
    String className = null;
    ClassSymbol extendedClass = null;

    for(int i = 0; i < this.jjtGetNumChildren(); i++)
    {
      SimpleNode child = (SimpleNode) this.jjtGetChild(i);

      switch(child.id)
      {
        case ParserTreeConstants.JJTVAR:
          child.setTables(table, newTable);
          child.eval();
          break;
        case ParserTreeConstants.JJTEXTEND:
          child.setTables(table, newTable);
          child.eval();
          extendedClass = ((ASTExtend) child).extendedClass;
          break;
        case ParserTreeConstants.JJTIDENTIFIER:
          ASTIdentifier temp = (ASTIdentifier) child;
          className = temp.identifierName;
          break;
        case ParserTreeConstants.JJTMETHOD:
          child.setTables(new SymbolTable(table), newTable);
          child.eval();
          break;
        default:
          throw new SemanticsException("Incorrect child node.");
      }
    }

    classSymbol = new ClassSymbol(className, newTable, extendedClass);
    table.putSymbol(className, classSymbol);

    for(int i = 0; i < this.jjtGetNumChildren(); i++) {
      SimpleNode child = (SimpleNode) this.jjtGetChild(i);
      if (child.id == ParserTreeConstants.JJTMETHOD) {
        ASTMethod method = (ASTMethod) child;
        method.processBody();
      }
    }
  }
}
/* JavaCC - OriginalChecksum=f92e5600b4d1b54c8cf65f0fa9dc9373 (do not edit this line) */
