package javamm.parser;

import javamm.semantics.Symbol.Type;

import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends BinaryOperatorNode {
  public ASTDiv(int id) {
    super(id,Type.INT,Type.INT);
  }

  public ASTDiv(Javamm p, int id) {
    super(p, id,Type.INT,Type.INT);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.INT};
  }

  @Override
  public void write(PrintWriter writer) {
    super.write(writer);
    writer.println("  idiv");
  }
}
/* JavaCC - OriginalChecksum=a6ae99679f76890aff99ebcee897988e (do not edit this line) */
