/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javamm.parser;

public
class ASTElse extends FlowControlNode {
  public ASTElse(int id) {
    super(id);
  }

  public ASTElse(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return "Else";
  }
}
/* JavaCC - OriginalChecksum=2c7a5fa98cea3452c51c6939f213edaa (do not edit this line) */
