package javamm.parser;
import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIf extends ConditionalNode {
  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public void write(PrintWriter writer) {
    //TODO implement this or leave blank to not call the default one
  }
}
/* JavaCC - OriginalChecksum=3f17c4ed5b4fd5cc052c1c2d168b79b9 (do not edit this line) */
