package javamm.parser;

import javamm.SemanticsException;
import javamm.semantics.Symbol;

/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodBody extends SimpleNode {
    public Symbol.Type returnValue = null;

    public ASTMethodBody(int id) {
        super(id);
    }

    public ASTMethodBody(Javamm p, int id) {
        super(p, id);
    }

    @Override
    public void eval(Javamm parser) {
        for (int i = 0; i < this.jjtGetNumChildren(); i++) {
            SimpleNode methodNode = (SimpleNode) this.jjtGetChild(i);
            methodNode.setTables(table, methodTable);
            methodNode.eval(parser);
            if (methodNode.id == JavammTreeConstants.JJTMETHODRETURN) {
                ASTMethodReturn methodReturn = (ASTMethodReturn) methodNode;
                methodReturn.setTables(table, methodTable);
                methodReturn.eval(parser);

                break;
            }
        }
    }

}
/* JavaCC - OriginalChecksum=5c687ef179ba60ab5c8f745d7c137cbc (do not edit this line) */
