package javamm.parser;

import javamm.semantics.Symbol.Type;
import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTMul.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMul extends BinaryOperatorNode {
  public ASTMul(int id) {
    super(id,Type.INT,Type.INT);
  }

  public ASTMul(Javamm p, int id) {
    super(p, id, Type.INT,Type.INT);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.INT};
  }

  @Override
  public void write(PrintWriter writer) {
    super.write(writer);
    writer.println("  imul");
  }
}
/* JavaCC - OriginalChecksum=e5abe143d74eea8d5312703bd5001c7a (do not edit this line) */
