/* Generated By:JJTree: Do not edit this line. ASTMethodReturn.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javamm.parser;

import javamm.SemanticsException;
import javamm.semantics.Symbol;

public
class ASTMethodReturn extends SimpleNode {
    Symbol.Type type = null;

    public ASTMethodReturn(int id) {
        super(id);
    }

    public ASTMethodReturn(Javamm p, int id) {
        super(p, id);
    }

    @Override
    public void eval(Javamm parser) {
        if (!(this.jjtGetChild(0) instanceof TypeNode)) {
            parser.semanticErrors.add(new SemanticsException("Unknown return type!", this));
            return;
        }

        final TypeNode node = (TypeNode) this.jjtGetChild(0);
        node.setTables(table, methodTable);
        node.eval(parser);
        type = node.type;
    }
}
/* JavaCC - OriginalChecksum=f35d6e18a29162cb6c0e550634450721 (do not edit this line) */
