/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javamm.parser;

public
class ASTProgram extends SimpleNode {
    public ASTProgram(int id) {
        super(id);
    }

    public ASTProgram(Javamm p, int id) {
        super(p, id);
    }

    public void eval(Javamm parser) {
        super.eval(parser);

        for(int i = 0; i< this.jjtGetNumChildren(); i++) {
            SimpleNode node = (SimpleNode) this.jjtGetChild(i);
            if (!(node instanceof ASTImport)) continue;

            ASTImport importNode = (ASTImport) node;
            importNode.evalIdentifiers(parser);
        }
    }

}
/* JavaCC - OriginalChecksum=a6621b64ae88273fafdfedc41d08c4b5 (do not edit this line) */
