package javamm.parser;

/* Generated By:JJTree: Do not edit this line. ASTRecoverFromError.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRecoverFromError extends SimpleNode {
  public ASTRecoverFromError(int id) {
    super(id);
  }

  public ASTRecoverFromError(Javamm p, int id) {
    super(p, id);
  }

  public void dump(String prefix) {
    super.dump( prefix + "(☞ﾟヮﾟ)☞  ");
  }
}
/* JavaCC - OriginalChecksum=b7245814adb330bcd5b66ba58df5548c (do not edit this line) */
