package javamm.parser;

import javamm.semantics.Symbol.Type;
import java.io.PrintWriter;
/* Generated By:JJTree: Do not edit this line. ASTSum.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSum extends BinaryOperatorNode {
  public ASTSum(int id) {
    super(id,Type.INT,Type.INT);
  }

  public ASTSum(Javamm p, int id) {
    super(p, id, Type.INT,Type.INT);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.INT};
  }

  @Override
  public void write(PrintWriter writer) {
    super.write(writer);
    writer.println("  iadd");
  }
}
/* JavaCC - OriginalChecksum=4ff6a21ad754b297da0cfd725ff9d094 (do not edit this line) */
