package javamm.parser;

import javamm.semantics.Symbol.Type;
import java.io.PrintWriter;

/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSub extends BinaryOperatorNode {
  public ASTSub(int id) {
    super(id,Type.INT,Type.INT);
  }

  public ASTSub(Javamm p, int id) {
    super(p, id,Type.INT,Type.INT);
  }

  @Override
  public Type[] getSupportedTypes() {
    return new Type[]{Type.INT};
  }

  @Override
  public void write(PrintWriter writer) {
    //TODO implement this or leave blank to not call the default one
  }
}
/* JavaCC - OriginalChecksum=b7fc14f4941a1c938c1b03e9740f85d8 (do not edit this line) */
