/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javamm.parser;

public
class ASTThen extends FlowControlNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return "Then";
  }
}
/* JavaCC - OriginalChecksum=445e904723e2053b1c85b403bf194598 (do not edit this line) */
