package javamm.parser;/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_Javamm=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import javamm.semantics.StackUsage;

public
class ASTVar extends VarNode {
  public ASTVar(int id) {
    super(id,false);
    this.validStatement = true;
  }

  public ASTVar(Javamm p, int id) {
    super(p, id,false);
    this.validStatement = true;
  }

  @Override
  protected void calculateStackUsage(StackUsage stackUsage) { }

}
/* JavaCC - OriginalChecksum=d3558354610a208fcf13fa1f04295551 (do not edit this line) */
