package javamm.parser;

/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 6.1_2 */
public interface JavammTreeConstants
{
    public int JJTPROGRAM = 0;
    public int JJTVOID = 1;
    public int JJTSTATIC = 2;
    public int JJTIMPORTPARAMS = 3;
    public int JJTRETURN = 4;
    public int JJTIMPORT = 5;
    public int JJTIDENTIFIER = 6;
    public int JJTEXTEND = 7;
    public int JJTCLASS = 8;
    public int JJTVAR = 9;
    public int JJTMETHODBODY = 10;
    public int JJTMAIN = 11;
    public int JJTMETHOD = 12;
    public int JJTMETHODNAME = 13;
    public int JJTPARAMETERS = 14;
    public int JJTIF = 15;
    public int JJTWHILE = 16;
    public int JJTASSIGNVAR = 17;
    public int JJTARRAYACCESS = 18;
    public int JJTASSIGNVARARRAY = 19;
    public int JJTRECOVERFROMERROR = 20;
    public int JJTCALL = 21;
    public int JJTINTARRAY = 22;
    public int JJTINT = 23;
    public int JJTBOOLEAN = 24;
    public int JJTAND = 25;
    public int JJTLESSTHAN = 26;
    public int JJTSUB = 27;
    public int JJTSUM = 28;
    public int JJTMUL = 29;
    public int JJTDIV = 30;
    public int JJTNEGATION = 31;
    public int JJTLENGTH = 32;
    public int JJTMETHODCALL = 33;
    public int JJTNUMERIC = 34;
    public int JJTBOOLEANVALUE = 35;
    public int JJTTHIS = 36;
    public int JJTNEW = 37;
    public int JJTNEWARRAY = 38;
    public int JJTMETHODRETURN = 39;
    public int JJTTHEN = 40;
    public int JJTELSE = 41;


    public String[] jjtNodeName = {
            "Program",
            "void",
            "Static",
            "ImportParams",
            "Return",
            "Import",
            "Identifier",
            "Extend",
            "Class",
            "Var",
            "MethodBody",
            "Main",
            "Method",
            "MethodName",
            "Parameters",
            "If",
            "While",
            "AssignVar",
            "ArrayAccess",
            "AssignVarArray",
            "RecoverFromError",
            "Call",
            "IntArray",
            "Int",
            "Boolean",
            "And",
            "LessThan",
            "Sub",
            "Sum",
            "Mul",
            "Div",
            "Negation",
            "Length",
            "MethodCall",
            "Numeric",
            "BooleanValue",
            "This",
            "New",
            "NewArray",
            "MethodReturn"
    };
}
/* JavaCC - OriginalChecksum=1eaead22e08643eb1c16fe97aed01532 (do not edit this line) */
