package base;

import base.semantics.Symbol;

/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodBody extends SimpleNode {
    public Symbol.Type returnValue = null;

    public ASTMethodBody(int id) {
        super(id);
    }

    public ASTMethodBody(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void eval() throws SemanticsException {
        int i = 0;
        for (; i < this.jjtGetNumChildren(); i++) {
            SimpleNode methodNode = (SimpleNode) this.jjtGetChild(i);
            methodNode.setTables(table, methodTable);
            methodNode.eval();
            if (methodNode.id == ParserTreeConstants.JJTMETHODRETURN) {
                ASTMethodReturn methodReturn = (ASTMethodReturn) methodNode;
                methodReturn.setTables(table, methodTable);
                methodReturn.eval();
                //TODO: Add return value
//                if (methodReturn.type != returnValue)
//                    throw new SemanticsException("Return value expected to be " + returnValue + " found " + methodReturn.type);
                break;
            }
        }
    }

}
/* JavaCC - OriginalChecksum=5c687ef179ba60ab5c8f745d7c137cbc (do not edit this line) */
