package base;

/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodBody extends SimpleNode {
  public ASTReturn returnValue = null;

  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws SemanticsException {
    int i = 0;
    for(; i < this.jjtGetNumChildren(); i++){
      SimpleNode methodNode = (SimpleNode) this.jjtGetChild(i);
      methodNode.setTable(table);
      methodNode.eval();
      if(methodNode.id == ParserTreeConstants.JJTRETURN){
        this.returnValue = (ASTReturn) methodNode;
        break;
      }
    }
  }

}
/* JavaCC - OriginalChecksum=5c687ef179ba60ab5c8f745d7c137cbc (do not edit this line) */
