package base;

/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodCall extends TypeNode {
    public ASTMethodCall(int id) {
        super(id);
    }

    public ASTMethodCall(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void eval() throws SemanticsException {
        if (this.jjtGetNumChildren() != 2) throw new SemanticsException("Wrong number of children found");

        final SimpleNode methodName = (SimpleNode) this.jjtGetChild(0);
        final ASTCall call = ((ASTCall) this.jjtGetChild(1));
        call.setTables(table, methodTable);
        if (methodName.id == ParserTreeConstants.JJTIDENTIFIER){
            final String methodIdentifier = ((ASTIdentifier) methodName).identifierName;
            //call.evalWithIdentifier(methodIdentifier);
            //TODO: do after changes in imports
        } else if(methodName.id == ParserTreeConstants.JJTTHIS)
            call.evalWithThis();

        this.type = call.type;


        //TODO: Get Method's return type


    }
}
/* JavaCC - OriginalChecksum=c431bc197d60321c47680450a6c0622a (do not edit this line) */
