package base;

/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws SemanticsException {

  }
}
/* JavaCC - OriginalChecksum=06378717be231427877699ba9f1e28a9 (do not edit this line) */
