package base;

import base.semantics.Symbol;

/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturn extends TypeNode {
  public Symbol.Type returnType;

  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void eval() throws SemanticsException {
    SimpleNode child = (SimpleNode) this.jjtGetChild(0);
    child.setTables(table, methodTable);
    child.eval();
    this.returnType = Symbol.getNodeSymbolType(child); //TODO does not support statements
  }
}
/* JavaCC - OriginalChecksum=0d7badc8de429fd7f39c8b2723d9a136 (do not edit this line) */
