package base;/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class ASTVar extends VarNode {
  public ASTVar(int id) {
    super(id,false);
  }

  public ASTVar(Parser p, int id) {
    super(p, id,false);
  }

}
/* JavaCC - OriginalChecksum=d3558354610a208fcf13fa1f04295551 (do not edit this line) */
